Last login: Mon Jan 13 09:01:58 on ttys000
anupsaud@Anups-MacBook-Pro anup810 % git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.github/

nothing added to commit but untracked files present (use "git add" to track)
anupsaud@Anups-MacBook-Pro anup810 % git add .
anupsaud@Anups-MacBook-Pro anup810 % git commit -m "update ReadMe"
[main b976ad1] update ReadMe
 1 file changed, 42 insertions(+)
 create mode 100644 .github/workflows/snake.yml
anupsaud@Anups-MacBook-Pro anup810 % git push
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 10 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 1.02 KiB | 1.02 MiB/s, done.
Total 5 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/anup810/anup810.git
 ! [remote rejected] main -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/snake.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/anup810/anup810.git'
anupsaud@Anups-MacBook-Pro anup810 % git remote set-url origin https://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@github.com/anup810/anup810.git
anupsaud@Anups-MacBook-Pro anup810 % git push
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 10 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 1.02 KiB | 1.02 MiB/s, done.
Total 5 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/anup810/anup810.git
 ! [remote rejected] main -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/snake.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/anup810/anup810.git'
anupsaud@Anups-MacBook-Pro anup810 % 
