name: Generate Snake Animation

# Controls when the workflow will run
on:
  # Run at 12:00 UTC every day
  schedule:
    - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on every push to the repository
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate the Snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: anup810
          outputs: dist/snake.svg

      # Commit the Snake animation to the repository
      - name: Commit and Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Updated Snake animation"
          add: "dist/snake.svg"

  update:
    name: Update GitHub Profile with Snake
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Push the generated Snake animation to the profile README
      - name: Push Snake to README
        run: |
          sed -i '/<!--snake-start-->/, /<!--snake-end-->/c\<!--snake-start-->\n![Snake animation](dist/snake.svg)\n<!--snake-end-->' README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with Snake animation" || echo "No changes to commit"
          git push
